<a href="https://colab.research.google.com/github/ajit-ai/Data_Science/blob/main/Generative_Adversarial_Network_(GAN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This code defines a simple Energy-Based Model (EBM) in PyTorch. It consists of two linear layers with a ReLU activation in between. The forward method calculates the energy of the input data. The code then creates an instance of the EBM, generates random data, calculates the energy, computes a loss (mean energy), and performs a backward pass to compute gradients. Finally, it prints the weights and biases of the first linear layer.

In [ ]:
import torch
import torch.nn as nn

class EBM(nn.Module):
    def __init__(self):
        super().__init__()
        self.energy = nn.Sequential(
            nn.Linear(784, 128),
            nn.ReLU(),
            nn.Linear(128, 1)
        )

    def forward(self, x):
        return self.energy(x)

model = EBM()
data = torch.randn(32, 784)
energy = model(data)
loss = torch.mean(energy)
loss.backward()
#print the EBM
print(model.energy[0].weight)
print(model.energy[0].bias)


Parameter containing:
tensor([[-0.0048, -0.0324, -0.0067,  ..., -0.0212,  0.0113,  0.0278],
        [-0.0040,  0.0056,  0.0200,  ...,  0.0206, -0.0206,  0.0269],
        [ 0.0114, -0.0131,  0.0068,  ...,  0.0078, -0.0011, -0.0028],
        ...,
        [ 0.0288, -0.0093,  0.0006,  ...,  0.0302,  0.0100,  0.0255],
        [ 0.0137,  0.0060,  0.0098,  ..., -0.0203, -0.0054,  0.0165],
        [ 0.0271,  0.0239, -0.0319,  ...,  0.0120, -0.0291,  0.0204]],
       requires_grad=True)
Parameter containing:
tensor([-5.7114e-04,  1.2744e-02, -9.4644e-03,  2.7943e-02,  3.0991e-02,
        -1.3808e-02, -1.0345e-02, -2.9528e-02,  6.9845e-04, -1.9041e-02,
        -8.3189e-03, -2.8257e-02, -7.7535e-03,  9.5194e-03, -1.0274e-02,
        -2.5109e-02,  3.1597e-02, -1.8261e-02, -5.9125e-03,  3.3080e-02,
        -6.9050e-03, -2.0067e-02, -2.2583e-02,  3.5697e-02,  2.6240e-02,
         3.3770e-02, -3.8324e-03, -3.0040e-02, -2.2496e-02,  4.1335e-03,
         1.3312e-02,  2.9333e-02, -2.1950e-02, -1.5341e-0

In [ ]:
import pymc as pm
import numpy as np

with pm.Model() as model:
    mu = pm.Normal('mu', mu=0, sigma=1)
    obs = pm.Normal('obs', mu=mu, sigma=1, observed=np.random.randn(100))
    trace = pm.sample(1000)
print(pm.summary(trace))

Output()

     mean     sd  hdi_3%  hdi_97%  mcse_mean  mcse_sd  ess_bulk  ess_tail  \
mu  0.048  0.103  -0.143    0.235      0.004    0.002     844.0    1386.0   

    r_hat  
mu    1.0  


In [ ]:
import torch
import torch.nn as nn

class DBN(nn.Module):
    def __init__(self):
        super().__init__()
        self.rbm1 = nn.Linear(784, 128)
        self.rbm2 = nn.Linear(128, 64)

    def forward(self, x):
        x = torch.sigmoid(self.rbm1(x))
        return torch.sigmoid(self.rbm2(x))

model = DBN()
data = torch.randn(32, 784)
output = model(data)

#print the DBN
print(model.rbm1.weight)
print(model.rbm1.bias)
print(model.rbm2.weight)
print(model.rbm2.bias)


Parameter containing:
tensor([[-0.0252,  0.0151,  0.0320,  ..., -0.0197, -0.0243,  0.0071],
        [ 0.0355,  0.0171,  0.0340,  ..., -0.0079, -0.0035, -0.0196],
        [ 0.0274,  0.0245,  0.0006,  ...,  0.0050,  0.0346, -0.0292],
        ...,
        [ 0.0227,  0.0045,  0.0330,  ..., -0.0069, -0.0047,  0.0146],
        [ 0.0160, -0.0139, -0.0077,  ..., -0.0257,  0.0237,  0.0255],
        [-0.0079,  0.0158, -0.0208,  ...,  0.0049, -0.0311, -0.0355]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0043,  0.0107,  0.0121,  0.0295, -0.0137, -0.0173, -0.0163, -0.0043,
         0.0284, -0.0327,  0.0088, -0.0152, -0.0157, -0.0005,  0.0191,  0.0290,
        -0.0237, -0.0315, -0.0185,  0.0167, -0.0261,  0.0218, -0.0074,  0.0070,
        -0.0012,  0.0263,  0.0298, -0.0197, -0.0010, -0.0225,  0.0150, -0.0106,
         0.0355, -0.0157, -0.0011, -0.0241, -0.0287, -0.0272, -0.0196, -0.0164,
        -0.0079, -0.0340,  0.0176,  0.0217, -0.0177,  0.0300,  0.0214,  0.0232,
         0.0255

In [ ]:
#!/usr/bin/env python

# Generative Adversarial Networks (GAN) example in PyTorch. Tested with PyTorch 0.4.1, Python 3.6.7 (Nov 2018)
# See related blog post at https://medium.com/@devnag/generative-adversarial-networks-gans-in-50-lines-of-code-pytorch-e81b79659e3f#.sch4xgsa9

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable

matplotlib_is_available = True
try:
  from matplotlib import pyplot as plt
except ImportError:
  print("Will skip plotting; matplotlib is not available.")
  matplotlib_is_available = False

# Data params
data_mean = 4
data_stddev = 1.25

# ### Uncomment only one of these to define what data is actually sent to the Discriminator
#(name, preprocess, d_input_func) = ("Raw data", lambda data: data, lambda x: x)
#(name, preprocess, d_input_func) = ("Data and variances", lambda data: decorate_with_diffs(data, 2.0), lambda x: x * 2)
#(name, preprocess, d_input_func) = ("Data and diffs", lambda data: decorate_with_diffs(data, 1.0), lambda x: x * 2)
(name, preprocess, d_input_func) = ("Only 4 moments", lambda data: get_moments(data), lambda x: 4)

print("Using data [%s]" % (name))

# ##### DATA: Target data and generator input data

def get_distribution_sampler(mu, sigma):
    return lambda n: torch.Tensor(np.random.normal(mu, sigma, (1, n)))  # Gaussian

def get_generator_input_sampler():
    return lambda m, n: torch.rand(m, n)  # Uniform-dist data into generator, _NOT_ Gaussian

# ##### MODELS: Generator model and discriminator model

class Generator(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, f):
        super(Generator, self).__init__()
        self.map1 = nn.Linear(input_size, hidden_size)
        self.map2 = nn.Linear(hidden_size, hidden_size)
        self.map3 = nn.Linear(hidden_size, output_size)
        self.f = f

    def forward(self, x):
        x = self.map1(x)
        x = self.f(x)
        x = self.map2(x)
        x = self.f(x)
        x = self.map3(x)
        return x

class Discriminator(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, f):
        super(Discriminator, self).__init__()
        self.map1 = nn.Linear(input_size, hidden_size)
        self.map2 = nn.Linear(hidden_size, hidden_size)
        self.map3 = nn.Linear(hidden_size, output_size)
        self.f = f

    def forward(self, x):
        x = self.f(self.map1(x))
        x = self.f(self.map2(x))
        return self.f(self.map3(x))

def extract(v):
    return v.data.storage().tolist()

def stats(d):
    return [np.mean(d), np.std(d)]

def get_moments(d):
    # Return the first 4 moments of the data provided
    mean = torch.mean(d)
    diffs = d - mean
    var = torch.mean(torch.pow(diffs, 2.0))
    std = torch.pow(var, 0.5)
    zscores = diffs / std
    skews = torch.mean(torch.pow(zscores, 3.0))
    kurtoses = torch.mean(torch.pow(zscores, 4.0)) - 3.0  # excess kurtosis, should be 0 for Gaussian
    final = torch.cat((mean.reshape(1,), std.reshape(1,), skews.reshape(1,), kurtoses.reshape(1,)))
    return final

def decorate_with_diffs(data, exponent, remove_raw_data=False):
    mean = torch.mean(data.data, 1, keepdim=True)
    mean_broadcast = torch.mul(torch.ones(data.size()), mean.tolist()[0][0])
    diffs = torch.pow(data - Variable(mean_broadcast), exponent)
    if remove_raw_data:
        return torch.cat([diffs], 1)
    else:
        return torch.cat([data, diffs], 1)

def train():
    # Model parameters
    g_input_size = 1      # Random noise dimension coming into generator, per output vector
    g_hidden_size = 5     # Generator complexity
    g_output_size = 1     # Size of generated output vector
    d_input_size = 500    # Minibatch size - cardinality of distributions
    d_hidden_size = 10    # Discriminator complexity
    d_output_size = 1     # Single dimension for 'real' vs. 'fake' classification
    minibatch_size = d_input_size

    d_learning_rate = 1e-3
    g_learning_rate = 1e-3
    sgd_momentum = 0.9

    num_epochs = 5000
    print_interval = 100
    d_steps = 20
    g_steps = 20

    dfe, dre, ge = 0, 0, 0
    d_real_data, d_fake_data, g_fake_data = None, None, None

    discriminator_activation_function = torch.sigmoid
    generator_activation_function = torch.tanh

    d_sampler = get_distribution_sampler(data_mean, data_stddev)
    gi_sampler = get_generator_input_sampler()
    G = Generator(input_size=g_input_size,
                  hidden_size=g_hidden_size,
                  output_size=g_output_size,
                  f=generator_activation_function)
    D = Discriminator(input_size=d_input_func(d_input_size),
                      hidden_size=d_hidden_size,
                      output_size=d_output_size,
                      f=discriminator_activation_function)
    criterion = nn.BCELoss()  # Binary cross entropy: http://pytorch.org/docs/nn.html#bceloss
    d_optimizer = optim.SGD(D.parameters(), lr=d_learning_rate, momentum=sgd_momentum)
    g_optimizer = optim.SGD(G.parameters(), lr=g_learning_rate, momentum=sgd_momentum)

    for epoch in range(num_epochs):
        for d_index in range(d_steps):
            # 1. Train D on real+fake
            D.zero_grad()

            #  1A: Train D on real
            d_real_data = Variable(d_sampler(d_input_size))
            d_real_decision = D(preprocess(d_real_data))
            d_real_error = criterion(d_real_decision, Variable(torch.ones([1])))  # ones = true
            d_real_error.backward() # compute/store gradients, but don't change params

            #  1B: Train D on fake
            d_gen_input = Variable(gi_sampler(minibatch_size, g_input_size))
            d_fake_data = G(d_gen_input).detach()  # detach to avoid training G on these labels
            d_fake_decision = D(preprocess(d_fake_data.t()))
            d_fake_error = criterion(d_fake_decision, Variable(torch.zeros([1])))  # zeros = fake
            d_fake_error.backward()
            d_optimizer.step()     # Only optimizes D's parameters; changes based on stored gradients from backward()

            dre, dfe = extract(d_real_error)[0], extract(d_fake_error)[0]

        for g_index in range(g_steps):
            # 2. Train G on D's response (but DO NOT train D on these labels)
            G.zero_grad()

            gen_input = Variable(gi_sampler(minibatch_size, g_input_size))
            g_fake_data = G(gen_input)
            dg_fake_decision = D(preprocess(g_fake_data.t()))
            g_error = criterion(dg_fake_decision, Variable(torch.ones([1])))  # Train G to pretend it's genuine

            g_error.backward()
            g_optimizer.step()  # Only optimizes G's parameters
            ge = extract(g_error)[0]

        if epoch % print_interval == 0:
            print("Epoch %s: D (%s real_err, %s fake_err) G (%s err); Real Dist (%s),  Fake Dist (%s) " %
                  (epoch, dre, dfe, ge, stats(extract(d_real_data)), stats(extract(d_fake_data))))

    if matplotlib_is_available:
        print("Plotting the generated distribution...")
        values = extract(g_fake_data)
        print(" Values: %s" % (str(values)))
        plt.hist(values, bins=50)
        plt.xlabel('Value')
        plt.ylabel('Count')
        plt.title('Histogram of Generated Distribution')
        plt.grid(True)
        plt.show()


train()

Using data [Only 4 moments]


/tmp/ipython-input-218584145.py:71: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return v.data.storage().tolist()


Epoch 0: D (0.712662935256958 real_err, 0.6756935119628906 fake_err) G (0.7100701332092285 err); Real Dist ([np.float64(3.9895897438824175), np.float64(1.2873772582119305)]),  Fake Dist ([np.float64(0.08323982346057891), np.float64(0.044101956037884714)]) 
Epoch 100: D (0.5484893918037415 real_err, 0.5568651556968689 fake_err) G (0.8226900696754456 err); Real Dist ([np.float64(3.996354756116867), np.float64(1.243705169233167)]),  Fake Dist ([np.float64(2.159198224067688), np.float64(0.052547054669080016)]) 
Epoch 200: D (0.2795944809913635 real_err, 0.27383261919021606 fake_err) G (0.49754464626312256 err); Real Dist ([np.float64(4.001707068443299), np.float64(1.1954162274508504)]),  Fake Dist ([np.float64(-4.956552453637123), np.float64(2.2410603054113643)]) 
Epoch 300: D (0.41367107629776 real_err, 0.3408621847629547 fake_err) G (1.2262970209121704 err); Real Dist ([np.float64(3.9655116587877273), np.float64(1.2475222646811097)]),  Fake Dist ([np.float64(6.00027772140503), np.float64